/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.auth.department.service.model.impl;

import com.swork.auth.department.service.model.DepartmentAccountEntry;
import com.swork.auth.department.service.service.DepartmentAccountEntryLocalServiceUtil;

/**
 * The extended model base implementation for the DepartmentAccountEntry service. Represents a row in the &quot;SW_DepartmentAccount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DepartmentAccountEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DepartmentAccountEntryImpl
 * @see DepartmentAccountEntry
 * @generated
 */
public abstract class DepartmentAccountEntryBaseImpl
	extends DepartmentAccountEntryModelImpl implements DepartmentAccountEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a department account entry model instance should use the <code>DepartmentAccountEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DepartmentAccountEntryLocalServiceUtil.addDepartmentAccountEntry(
				this);
		}
		else {
			DepartmentAccountEntryLocalServiceUtil.updateDepartmentAccountEntry(
				this);
		}
	}

}