/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.core.phase.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PhaseEntry service. Represents a row in the &quot;SW_Phase&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.swork.core.phase.service.model.impl.PhaseEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.swork.core.phase.service.model.impl.PhaseEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PhaseEntry
 * @generated
 */
@ProviderType
public interface PhaseEntryModel
	extends BaseModel<PhaseEntry>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a phase entry model instance should use the {@link PhaseEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this phase entry.
	 *
	 * @return the primary key of this phase entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this phase entry.
	 *
	 * @param primaryKey the primary key of this phase entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this phase entry.
	 *
	 * @return the uuid of this phase entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this phase entry.
	 *
	 * @param uuid the uuid of this phase entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this phase entry.
	 *
	 * @return the external reference code of this phase entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this phase entry.
	 *
	 * @param externalReferenceCode the external reference code of this phase entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the phase ID of this phase entry.
	 *
	 * @return the phase ID of this phase entry
	 */
	public long getPhaseId();

	/**
	 * Sets the phase ID of this phase entry.
	 *
	 * @param phaseId the phase ID of this phase entry
	 */
	public void setPhaseId(long phaseId);

	/**
	 * Returns the group ID of this phase entry.
	 *
	 * @return the group ID of this phase entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this phase entry.
	 *
	 * @param groupId the group ID of this phase entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this phase entry.
	 *
	 * @return the company ID of this phase entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this phase entry.
	 *
	 * @param companyId the company ID of this phase entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the creator ID of this phase entry.
	 *
	 * @return the creator ID of this phase entry
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this phase entry.
	 *
	 * @param creatorId the creator ID of this phase entry
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the create date of this phase entry.
	 *
	 * @return the create date of this phase entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this phase entry.
	 *
	 * @param createDate the create date of this phase entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this phase entry.
	 *
	 * @return the modified date of this phase entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this phase entry.
	 *
	 * @param modifiedDate the modified date of this phase entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the business ID of this phase entry.
	 *
	 * @return the business ID of this phase entry
	 */
	public long getBusinessId();

	/**
	 * Sets the business ID of this phase entry.
	 *
	 * @param businessId the business ID of this phase entry
	 */
	public void setBusinessId(long businessId);

	/**
	 * Returns the modified ID of this phase entry.
	 *
	 * @return the modified ID of this phase entry
	 */
	public long getModifiedId();

	/**
	 * Sets the modified ID of this phase entry.
	 *
	 * @param modifiedId the modified ID of this phase entry
	 */
	public void setModifiedId(long modifiedId);

	/**
	 * Returns the phase name of this phase entry.
	 *
	 * @return the phase name of this phase entry
	 */
	@AutoEscape
	public String getPhaseName();

	/**
	 * Sets the phase name of this phase entry.
	 *
	 * @param phaseName the phase name of this phase entry
	 */
	public void setPhaseName(String phaseName);

	/**
	 * Returns the start date of this phase entry.
	 *
	 * @return the start date of this phase entry
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this phase entry.
	 *
	 * @param startDate the start date of this phase entry
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this phase entry.
	 *
	 * @return the end date of this phase entry
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this phase entry.
	 *
	 * @param endDate the end date of this phase entry
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the status of this phase entry.
	 *
	 * @return the status of this phase entry
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this phase entry.
	 *
	 * @param status the status of this phase entry
	 */
	public void setStatus(String status);

	/**
	 * Returns the description of this phase entry.
	 *
	 * @return the description of this phase entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this phase entry.
	 *
	 * @param description the description of this phase entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the progress of this phase entry.
	 *
	 * @return the progress of this phase entry
	 */
	public long getProgress();

	/**
	 * Sets the progress of this phase entry.
	 *
	 * @param progress the progress of this phase entry
	 */
	public void setProgress(long progress);

	/**
	 * Returns the project ID of this phase entry.
	 *
	 * @return the project ID of this phase entry
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this phase entry.
	 *
	 * @param projectId the project ID of this phase entry
	 */
	public void setProjectId(long projectId);

	@Override
	public PhaseEntry cloneWithOriginalValues();

}