/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.core.phase.service.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PhaseManageEntry service. Represents a row in the &quot;SW_PhaseManage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.swork.core.phase.service.model.impl.PhaseManageEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.swork.core.phase.service.model.impl.PhaseManageEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PhaseManageEntry
 * @generated
 */
@ProviderType
public interface PhaseManageEntryModel extends BaseModel<PhaseManageEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a phase manage entry model instance should use the {@link PhaseManageEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this phase manage entry.
	 *
	 * @return the primary key of this phase manage entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this phase manage entry.
	 *
	 * @param primaryKey the primary key of this phase manage entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the phase manage ID of this phase manage entry.
	 *
	 * @return the phase manage ID of this phase manage entry
	 */
	public long getPhaseManageId();

	/**
	 * Sets the phase manage ID of this phase manage entry.
	 *
	 * @param phaseManageId the phase manage ID of this phase manage entry
	 */
	public void setPhaseManageId(long phaseManageId);

	/**
	 * Returns the phase ID of this phase manage entry.
	 *
	 * @return the phase ID of this phase manage entry
	 */
	public long getPhaseId();

	/**
	 * Sets the phase ID of this phase manage entry.
	 *
	 * @param phaseId the phase ID of this phase manage entry
	 */
	public void setPhaseId(long phaseId);

	/**
	 * Returns the account ID of this phase manage entry.
	 *
	 * @return the account ID of this phase manage entry
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this phase manage entry.
	 *
	 * @param accountId the account ID of this phase manage entry
	 */
	public void setAccountId(long accountId);

	@Override
	public PhaseManageEntry cloneWithOriginalValues();

}