apiDir: "../notification-rest-api/src/main/java"
apiPackagePath: "com.swork.notification.rest"
application:
    baseURI: "/swork/notification-rest"
    className: "NotificationRestApplication"
    name: "NotificationRest"
author: "longnv"
clientDir: "../notification-rest-client/src/main/java"
testDir: "../notification-rest-test/src/testIntegration/java"