/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.core.phase.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.swork.core.phase.service.model.PhaseManageEntry;
import com.swork.core.phase.service.model.PhaseManageEntryModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PhaseManageEntry service. Represents a row in the &quot;SW_PhaseManage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PhaseManageEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PhaseManageEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PhaseManageEntryImpl
 * @generated
 */
public class PhaseManageEntryModelImpl
	extends BaseModelImpl<PhaseManageEntry> implements PhaseManageEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a phase manage entry model instance should use the <code>PhaseManageEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "SW_PhaseManage";

	public static final Object[][] TABLE_COLUMNS = {
		{"phaseManageId", Types.BIGINT}, {"phaseId", Types.BIGINT},
		{"accountId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("phaseManageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("phaseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("accountId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SW_PhaseManage (phaseManageId LONG not null primary key,phaseId LONG,accountId LONG)";

	public static final String TABLE_SQL_DROP = "drop table SW_PhaseManage";

	public static final String ORDER_BY_JPQL =
		" ORDER BY phaseManageEntry.phaseManageId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SW_PhaseManage.phaseManageId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PHASEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PHASEMANAGEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PhaseManageEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _phaseManageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPhaseManageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _phaseManageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PhaseManageEntry.class;
	}

	@Override
	public String getModelClassName() {
		return PhaseManageEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PhaseManageEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PhaseManageEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PhaseManageEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PhaseManageEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PhaseManageEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PhaseManageEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PhaseManageEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PhaseManageEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PhaseManageEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, PhaseManageEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			PhaseManageEntry.class.getClassLoader(), PhaseManageEntry.class,
			ModelWrapper.class);

		try {
			Constructor<PhaseManageEntry> constructor =
				(Constructor<PhaseManageEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<PhaseManageEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PhaseManageEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PhaseManageEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<PhaseManageEntry, Object>>();
		Map<String, BiConsumer<PhaseManageEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<PhaseManageEntry, ?>>();

		attributeGetterFunctions.put(
			"phaseManageId", PhaseManageEntry::getPhaseManageId);
		attributeSetterBiConsumers.put(
			"phaseManageId",
			(BiConsumer<PhaseManageEntry, Long>)
				PhaseManageEntry::setPhaseManageId);
		attributeGetterFunctions.put("phaseId", PhaseManageEntry::getPhaseId);
		attributeSetterBiConsumers.put(
			"phaseId",
			(BiConsumer<PhaseManageEntry, Long>)PhaseManageEntry::setPhaseId);
		attributeGetterFunctions.put(
			"accountId", PhaseManageEntry::getAccountId);
		attributeSetterBiConsumers.put(
			"accountId",
			(BiConsumer<PhaseManageEntry, Long>)PhaseManageEntry::setAccountId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getPhaseManageId() {
		return _phaseManageId;
	}

	@Override
	public void setPhaseManageId(long phaseManageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phaseManageId = phaseManageId;
	}

	@Override
	public long getPhaseId() {
		return _phaseId;
	}

	@Override
	public void setPhaseId(long phaseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phaseId = phaseId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPhaseId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("phaseId"));
	}

	@Override
	public long getAccountId() {
		return _accountId;
	}

	@Override
	public void setAccountId(long accountId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accountId = accountId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, PhaseManageEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PhaseManageEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PhaseManageEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PhaseManageEntryImpl phaseManageEntryImpl = new PhaseManageEntryImpl();

		phaseManageEntryImpl.setPhaseManageId(getPhaseManageId());
		phaseManageEntryImpl.setPhaseId(getPhaseId());
		phaseManageEntryImpl.setAccountId(getAccountId());

		phaseManageEntryImpl.resetOriginalValues();

		return phaseManageEntryImpl;
	}

	@Override
	public PhaseManageEntry cloneWithOriginalValues() {
		PhaseManageEntryImpl phaseManageEntryImpl = new PhaseManageEntryImpl();

		phaseManageEntryImpl.setPhaseManageId(
			this.<Long>getColumnOriginalValue("phaseManageId"));
		phaseManageEntryImpl.setPhaseId(
			this.<Long>getColumnOriginalValue("phaseId"));
		phaseManageEntryImpl.setAccountId(
			this.<Long>getColumnOriginalValue("accountId"));

		return phaseManageEntryImpl;
	}

	@Override
	public int compareTo(PhaseManageEntry phaseManageEntry) {
		long primaryKey = phaseManageEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PhaseManageEntry)) {
			return false;
		}

		PhaseManageEntry phaseManageEntry = (PhaseManageEntry)object;

		long primaryKey = phaseManageEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PhaseManageEntry> toCacheModel() {
		PhaseManageEntryCacheModel phaseManageEntryCacheModel =
			new PhaseManageEntryCacheModel();

		phaseManageEntryCacheModel.phaseManageId = getPhaseManageId();

		phaseManageEntryCacheModel.phaseId = getPhaseId();

		phaseManageEntryCacheModel.accountId = getAccountId();

		return phaseManageEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PhaseManageEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PhaseManageEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PhaseManageEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(PhaseManageEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PhaseManageEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PhaseManageEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PhaseManageEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((PhaseManageEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PhaseManageEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _phaseManageId;
	private long _phaseId;
	private long _accountId;

	public <T> T getColumnValue(String columnName) {
		Function<PhaseManageEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PhaseManageEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("phaseManageId", _phaseManageId);
		_columnOriginalValues.put("phaseId", _phaseId);
		_columnOriginalValues.put("accountId", _accountId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("phaseManageId", 1L);

		columnBitmasks.put("phaseId", 2L);

		columnBitmasks.put("accountId", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PhaseManageEntry _escapedModel;

}