apiDir: "../common-comment-rest-api/src/main/java"
apiPackagePath: "com.swork.common.comment.rest"
application:
    baseURI: "/swork/common-comment-rest"
    className: "CommonCommentRestApplication"
    name: "CommonCommentRest"
author: "Long Hip"
clientDir: "../common-comment-rest-client/src/main/java"
testDir: "../common-comment-rest-test/src/testIntegration/java"