/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.checklist.service.model.impl;

import com.swork.checklist.service.model.ChecklistHandlerEntry;
import com.swork.checklist.service.service.ChecklistHandlerEntryLocalServiceUtil;

/**
 * The extended model base implementation for the ChecklistHandlerEntry service. Represents a row in the &quot;SW_ChecklistHandler&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChecklistHandlerEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChecklistHandlerEntryImpl
 * @see ChecklistHandlerEntry
 * @generated
 */
public abstract class ChecklistHandlerEntryBaseImpl
	extends ChecklistHandlerEntryModelImpl implements ChecklistHandlerEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a checklist handler entry model instance should use the <code>ChecklistHandlerEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ChecklistHandlerEntryLocalServiceUtil.addChecklistHandlerEntry(
				this);
		}
		else {
			ChecklistHandlerEntryLocalServiceUtil.updateChecklistHandlerEntry(
				this);
		}
	}

}