components:
  schemas:
    CheckList:
      type: object
      properties:
        checkListId:
          type: integer
          format: int64
        name:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        taskId:
          type: integer
          format: int64
        status:
          type: boolean
        handlers:
          type: array
          items:
            type: integer
            format: int64


info:
  description: "ChecklistRest REST API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  title: "ChecklistRest"
  version: v1.0
openapi: 3.0.1

paths:
  "/checklist":
    get:
      tags: [ "Checklist" ]
      description:
        Retrieves the checklist. Results can be paginated, filtered, searched, and sorted.
      operationId: getChecklistPages
      parameters:
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: search
          schema:
            type: string
        - in: query
          name: sort
          schema:
            type: string
      responses:
        200:
          description: The data returned
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/CheckList"
                type: array
            application/xml:
              schema:
                items:
                  $ref: "#/components/schemas/CheckList"
                type: array


    post:
      operationId: postCheckList
      tags: [ "Checklist" ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckList'
          application/xml:
            schema:
              $ref: '#/components/schemas/CheckList'
      responses:
        200:
          description: "Create a CheckList"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckList'
            application/xml:
              schema:
                $ref: '#/components/schemas/CheckList'

  "/checklist/change-status/{cid}":
    put:
      operationId: changeCheckListStatusById
      tags: [ "Checklist" ]
      parameters:
        - name: cid
          in: path
          schema:
            type: integer
            format: int64
          required: true
        - name: status
          in: query
          schema:
            type: boolean
          required: true
      responses:
        200:
          description: "Change CheckList Status by Id"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckList'
            application/xml:
              schema:
                $ref: '#/components/schemas/CheckList'

  "/checklist/{cid}":
    get:
      operationId: getCheckListById
      tags: [ "Checklist" ]
      parameters:
        - name: cid
          in: path
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: "Get CheckList by Id"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckList'
            application/xml:
              schema:
                $ref: '#/components/schemas/CheckList'



    delete:
      operationId: deleteCheckList
      tags: [ "Checklist" ]
      parameters:
        - name: cid
          in: path
          schema:
            type: integer
            format: int64
          required: true
      responses:
        204:
          description: "Delete a CheckList"
          content:
            application/json: { }
            application/xml: { }

    put:
      operationId: updateCheckList
      tags: [ "Checklist" ]
      parameters:
        - name: cid
          in: path
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckList'
          application/xml:
            schema:
              $ref: '#/components/schemas/CheckList'
      responses:
        200:
          description: "Update a CheckList"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckList'
            application/xml:
              schema:
                $ref: '#/components/schemas/CheckList'