/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.core.work.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.swork.core.work.service.model.WorkEntry;
import com.swork.core.work.service.model.WorkEntryModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WorkEntry service. Represents a row in the &quot;SW_Work&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WorkEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WorkEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WorkEntryImpl
 * @generated
 */
public class WorkEntryModelImpl
	extends BaseModelImpl<WorkEntry> implements WorkEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a work entry model instance should use the <code>WorkEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "SW_Work";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"workId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"accountId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"modifiedId", Types.BIGINT}, {"businessId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"phaseId", Types.BIGINT},
		{"parentId", Types.BIGINT}, {"parentReferenceCode", Types.VARCHAR},
		{"progress", Types.BIGINT}, {"name", Types.VARCHAR},
		{"startDate", Types.TIMESTAMP}, {"endDate", Types.TIMESTAMP},
		{"actualStartDate", Types.TIMESTAMP},
		{"actualEndDate", Types.TIMESTAMP}, {"description", Types.VARCHAR},
		{"status", Types.VARCHAR}, {"percentage", Types.DOUBLE},
		{"progressType", Types.VARCHAR}, {"unit", Types.VARCHAR},
		{"incompleteAmount", Types.DOUBLE}, {"completeAmount", Types.DOUBLE},
		{"proportion", Types.BIGINT}, {"equalProportions", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("workId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("accountId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("businessId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("phaseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("progress", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("actualStartDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("actualEndDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("percentage", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("progressType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("unit", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("incompleteAmount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("completeAmount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("proportion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("equalProportions", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SW_Work (uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,workId LONG not null primary key,groupId LONG,companyId LONG,accountId LONG,createDate DATE null,modifiedDate DATE null,modifiedId LONG,businessId LONG,projectId LONG,phaseId LONG,parentId LONG,parentReferenceCode VARCHAR(75) null,progress LONG,name VARCHAR(100) null,startDate DATE null,endDate DATE null,actualStartDate DATE null,actualEndDate DATE null,description VARCHAR(75) null,status VARCHAR(75) null,percentage DOUBLE,progressType VARCHAR(75) null,unit VARCHAR(75) null,incompleteAmount DOUBLE,completeAmount DOUBLE,proportion LONG,equalProportions BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table SW_Work";

	public static final String ORDER_BY_JPQL = " ORDER BY workEntry.workId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY SW_Work.workId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BUSINESSID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARENTID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARENTREFERENCECODE_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PHASEID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROJECTID_COLUMN_BITMASK = 256L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 512L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long WORKID_COLUMN_BITMASK = 1024L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public WorkEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _workId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWorkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _workId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WorkEntry.class;
	}

	@Override
	public String getModelClassName() {
		return WorkEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WorkEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WorkEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WorkEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((WorkEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WorkEntry, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WorkEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WorkEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WorkEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WorkEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, WorkEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			WorkEntry.class.getClassLoader(), WorkEntry.class,
			ModelWrapper.class);

		try {
			Constructor<WorkEntry> constructor =
				(Constructor<WorkEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<WorkEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<WorkEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<WorkEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<WorkEntry, Object>>();
		Map<String, BiConsumer<WorkEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<WorkEntry, ?>>();

		attributeGetterFunctions.put("uuid", WorkEntry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<WorkEntry, String>)WorkEntry::setUuid);
		attributeGetterFunctions.put(
			"externalReferenceCode", WorkEntry::getExternalReferenceCode);
		attributeSetterBiConsumers.put(
			"externalReferenceCode",
			(BiConsumer<WorkEntry, String>)WorkEntry::setExternalReferenceCode);
		attributeGetterFunctions.put("workId", WorkEntry::getWorkId);
		attributeSetterBiConsumers.put(
			"workId", (BiConsumer<WorkEntry, Long>)WorkEntry::setWorkId);
		attributeGetterFunctions.put("groupId", WorkEntry::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<WorkEntry, Long>)WorkEntry::setGroupId);
		attributeGetterFunctions.put("companyId", WorkEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<WorkEntry, Long>)WorkEntry::setCompanyId);
		attributeGetterFunctions.put("accountId", WorkEntry::getAccountId);
		attributeSetterBiConsumers.put(
			"accountId", (BiConsumer<WorkEntry, Long>)WorkEntry::setAccountId);
		attributeGetterFunctions.put("createDate", WorkEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<WorkEntry, Date>)WorkEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", WorkEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<WorkEntry, Date>)WorkEntry::setModifiedDate);
		attributeGetterFunctions.put("modifiedId", WorkEntry::getModifiedId);
		attributeSetterBiConsumers.put(
			"modifiedId",
			(BiConsumer<WorkEntry, Long>)WorkEntry::setModifiedId);
		attributeGetterFunctions.put("businessId", WorkEntry::getBusinessId);
		attributeSetterBiConsumers.put(
			"businessId",
			(BiConsumer<WorkEntry, Long>)WorkEntry::setBusinessId);
		attributeGetterFunctions.put("projectId", WorkEntry::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId", (BiConsumer<WorkEntry, Long>)WorkEntry::setProjectId);
		attributeGetterFunctions.put("phaseId", WorkEntry::getPhaseId);
		attributeSetterBiConsumers.put(
			"phaseId", (BiConsumer<WorkEntry, Long>)WorkEntry::setPhaseId);
		attributeGetterFunctions.put("parentId", WorkEntry::getParentId);
		attributeSetterBiConsumers.put(
			"parentId", (BiConsumer<WorkEntry, Long>)WorkEntry::setParentId);
		attributeGetterFunctions.put(
			"parentReferenceCode", WorkEntry::getParentReferenceCode);
		attributeSetterBiConsumers.put(
			"parentReferenceCode",
			(BiConsumer<WorkEntry, String>)WorkEntry::setParentReferenceCode);
		attributeGetterFunctions.put("progress", WorkEntry::getProgress);
		attributeSetterBiConsumers.put(
			"progress", (BiConsumer<WorkEntry, Long>)WorkEntry::setProgress);
		attributeGetterFunctions.put("name", WorkEntry::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<WorkEntry, String>)WorkEntry::setName);
		attributeGetterFunctions.put("startDate", WorkEntry::getStartDate);
		attributeSetterBiConsumers.put(
			"startDate", (BiConsumer<WorkEntry, Date>)WorkEntry::setStartDate);
		attributeGetterFunctions.put("endDate", WorkEntry::getEndDate);
		attributeSetterBiConsumers.put(
			"endDate", (BiConsumer<WorkEntry, Date>)WorkEntry::setEndDate);
		attributeGetterFunctions.put(
			"actualStartDate", WorkEntry::getActualStartDate);
		attributeSetterBiConsumers.put(
			"actualStartDate",
			(BiConsumer<WorkEntry, Date>)WorkEntry::setActualStartDate);
		attributeGetterFunctions.put(
			"actualEndDate", WorkEntry::getActualEndDate);
		attributeSetterBiConsumers.put(
			"actualEndDate",
			(BiConsumer<WorkEntry, Date>)WorkEntry::setActualEndDate);
		attributeGetterFunctions.put("description", WorkEntry::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<WorkEntry, String>)WorkEntry::setDescription);
		attributeGetterFunctions.put("status", WorkEntry::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<WorkEntry, String>)WorkEntry::setStatus);
		attributeGetterFunctions.put("percentage", WorkEntry::getPercentage);
		attributeSetterBiConsumers.put(
			"percentage",
			(BiConsumer<WorkEntry, Double>)WorkEntry::setPercentage);
		attributeGetterFunctions.put(
			"progressType", WorkEntry::getProgressType);
		attributeSetterBiConsumers.put(
			"progressType",
			(BiConsumer<WorkEntry, String>)WorkEntry::setProgressType);
		attributeGetterFunctions.put("unit", WorkEntry::getUnit);
		attributeSetterBiConsumers.put(
			"unit", (BiConsumer<WorkEntry, String>)WorkEntry::setUnit);
		attributeGetterFunctions.put(
			"incompleteAmount", WorkEntry::getIncompleteAmount);
		attributeSetterBiConsumers.put(
			"incompleteAmount",
			(BiConsumer<WorkEntry, Double>)WorkEntry::setIncompleteAmount);
		attributeGetterFunctions.put(
			"completeAmount", WorkEntry::getCompleteAmount);
		attributeSetterBiConsumers.put(
			"completeAmount",
			(BiConsumer<WorkEntry, Double>)WorkEntry::setCompleteAmount);
		attributeGetterFunctions.put("proportion", WorkEntry::getProportion);
		attributeSetterBiConsumers.put(
			"proportion",
			(BiConsumer<WorkEntry, Long>)WorkEntry::setProportion);
		attributeGetterFunctions.put(
			"equalProportions", WorkEntry::getEqualProportions);
		attributeSetterBiConsumers.put(
			"equalProportions",
			(BiConsumer<WorkEntry, Boolean>)WorkEntry::setEqualProportions);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@Override
	public long getWorkId() {
		return _workId;
	}

	@Override
	public void setWorkId(long workId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workId = workId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getAccountId() {
		return _accountId;
	}

	@Override
	public void setAccountId(long accountId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accountId = accountId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getModifiedId() {
		return _modifiedId;
	}

	@Override
	public void setModifiedId(long modifiedId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedId = modifiedId;
	}

	@Override
	public long getBusinessId() {
		return _businessId;
	}

	@Override
	public void setBusinessId(long businessId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_businessId = businessId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalBusinessId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("businessId"));
	}

	@Override
	public Long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(Long projectId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_projectId = projectId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Long getOriginalProjectId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("projectId"));
	}

	@Override
	public Long getPhaseId() {
		return _phaseId;
	}

	@Override
	public void setPhaseId(Long phaseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phaseId = phaseId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Long getOriginalPhaseId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("phaseId"));
	}

	@Override
	public Long getParentId() {
		return _parentId;
	}

	@Override
	public void setParentId(Long parentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentId = parentId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Long getOriginalParentId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("parentId"));
	}

	@Override
	public String getParentReferenceCode() {
		if (_parentReferenceCode == null) {
			return "";
		}
		else {
			return _parentReferenceCode;
		}
	}

	@Override
	public void setParentReferenceCode(String parentReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentReferenceCode = parentReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalParentReferenceCode() {
		return getColumnOriginalValue("parentReferenceCode");
	}

	@Override
	public long getProgress() {
		return _progress;
	}

	@Override
	public void setProgress(long progress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_progress = progress;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	@Override
	public Date getActualStartDate() {
		return _actualStartDate;
	}

	@Override
	public void setActualStartDate(Date actualStartDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_actualStartDate = actualStartDate;
	}

	@Override
	public Date getActualEndDate() {
		return _actualEndDate;
	}

	@Override
	public void setActualEndDate(Date actualEndDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_actualEndDate = actualEndDate;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public double getPercentage() {
		return _percentage;
	}

	@Override
	public void setPercentage(double percentage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_percentage = percentage;
	}

	@Override
	public String getProgressType() {
		if (_progressType == null) {
			return "";
		}
		else {
			return _progressType;
		}
	}

	@Override
	public void setProgressType(String progressType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_progressType = progressType;
	}

	@Override
	public String getUnit() {
		if (_unit == null) {
			return "";
		}
		else {
			return _unit;
		}
	}

	@Override
	public void setUnit(String unit) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_unit = unit;
	}

	@Override
	public double getIncompleteAmount() {
		return _incompleteAmount;
	}

	@Override
	public void setIncompleteAmount(double incompleteAmount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_incompleteAmount = incompleteAmount;
	}

	@Override
	public double getCompleteAmount() {
		return _completeAmount;
	}

	@Override
	public void setCompleteAmount(double completeAmount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_completeAmount = completeAmount;
	}

	@Override
	public long getProportion() {
		return _proportion;
	}

	@Override
	public void setProportion(long proportion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_proportion = proportion;
	}

	@Override
	public Boolean getEqualProportions() {
		return _equalProportions;
	}

	@Override
	public void setEqualProportions(Boolean equalProportions) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_equalProportions = equalProportions;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(WorkEntry.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), WorkEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public WorkEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, WorkEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WorkEntryImpl workEntryImpl = new WorkEntryImpl();

		workEntryImpl.setUuid(getUuid());
		workEntryImpl.setExternalReferenceCode(getExternalReferenceCode());
		workEntryImpl.setWorkId(getWorkId());
		workEntryImpl.setGroupId(getGroupId());
		workEntryImpl.setCompanyId(getCompanyId());
		workEntryImpl.setAccountId(getAccountId());
		workEntryImpl.setCreateDate(getCreateDate());
		workEntryImpl.setModifiedDate(getModifiedDate());
		workEntryImpl.setModifiedId(getModifiedId());
		workEntryImpl.setBusinessId(getBusinessId());
		workEntryImpl.setProjectId(getProjectId());
		workEntryImpl.setPhaseId(getPhaseId());
		workEntryImpl.setParentId(getParentId());
		workEntryImpl.setParentReferenceCode(getParentReferenceCode());
		workEntryImpl.setProgress(getProgress());
		workEntryImpl.setName(getName());
		workEntryImpl.setStartDate(getStartDate());
		workEntryImpl.setEndDate(getEndDate());
		workEntryImpl.setActualStartDate(getActualStartDate());
		workEntryImpl.setActualEndDate(getActualEndDate());
		workEntryImpl.setDescription(getDescription());
		workEntryImpl.setStatus(getStatus());
		workEntryImpl.setPercentage(getPercentage());
		workEntryImpl.setProgressType(getProgressType());
		workEntryImpl.setUnit(getUnit());
		workEntryImpl.setIncompleteAmount(getIncompleteAmount());
		workEntryImpl.setCompleteAmount(getCompleteAmount());
		workEntryImpl.setProportion(getProportion());
		workEntryImpl.setEqualProportions(getEqualProportions());

		workEntryImpl.resetOriginalValues();

		return workEntryImpl;
	}

	@Override
	public WorkEntry cloneWithOriginalValues() {
		WorkEntryImpl workEntryImpl = new WorkEntryImpl();

		workEntryImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		workEntryImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		workEntryImpl.setWorkId(this.<Long>getColumnOriginalValue("workId"));
		workEntryImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		workEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		workEntryImpl.setAccountId(
			this.<Long>getColumnOriginalValue("accountId"));
		workEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		workEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		workEntryImpl.setModifiedId(
			this.<Long>getColumnOriginalValue("modifiedId"));
		workEntryImpl.setBusinessId(
			this.<Long>getColumnOriginalValue("businessId"));
		workEntryImpl.setProjectId(
			this.<Long>getColumnOriginalValue("projectId"));
		workEntryImpl.setPhaseId(this.<Long>getColumnOriginalValue("phaseId"));
		workEntryImpl.setParentId(
			this.<Long>getColumnOriginalValue("parentId"));
		workEntryImpl.setParentReferenceCode(
			this.<String>getColumnOriginalValue("parentReferenceCode"));
		workEntryImpl.setProgress(
			this.<Long>getColumnOriginalValue("progress"));
		workEntryImpl.setName(this.<String>getColumnOriginalValue("name"));
		workEntryImpl.setStartDate(
			this.<Date>getColumnOriginalValue("startDate"));
		workEntryImpl.setEndDate(this.<Date>getColumnOriginalValue("endDate"));
		workEntryImpl.setActualStartDate(
			this.<Date>getColumnOriginalValue("actualStartDate"));
		workEntryImpl.setActualEndDate(
			this.<Date>getColumnOriginalValue("actualEndDate"));
		workEntryImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		workEntryImpl.setStatus(this.<String>getColumnOriginalValue("status"));
		workEntryImpl.setPercentage(
			this.<Double>getColumnOriginalValue("percentage"));
		workEntryImpl.setProgressType(
			this.<String>getColumnOriginalValue("progressType"));
		workEntryImpl.setUnit(this.<String>getColumnOriginalValue("unit"));
		workEntryImpl.setIncompleteAmount(
			this.<Double>getColumnOriginalValue("incompleteAmount"));
		workEntryImpl.setCompleteAmount(
			this.<Double>getColumnOriginalValue("completeAmount"));
		workEntryImpl.setProportion(
			this.<Long>getColumnOriginalValue("proportion"));
		workEntryImpl.setEqualProportions(
			this.<Boolean>getColumnOriginalValue("equalProportions"));

		return workEntryImpl;
	}

	@Override
	public int compareTo(WorkEntry workEntry) {
		long primaryKey = workEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof WorkEntry)) {
			return false;
		}

		WorkEntry workEntry = (WorkEntry)object;

		long primaryKey = workEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<WorkEntry> toCacheModel() {
		WorkEntryCacheModel workEntryCacheModel = new WorkEntryCacheModel();

		workEntryCacheModel.uuid = getUuid();

		String uuid = workEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			workEntryCacheModel.uuid = null;
		}

		workEntryCacheModel.externalReferenceCode = getExternalReferenceCode();

		String externalReferenceCode =
			workEntryCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			workEntryCacheModel.externalReferenceCode = null;
		}

		workEntryCacheModel.workId = getWorkId();

		workEntryCacheModel.groupId = getGroupId();

		workEntryCacheModel.companyId = getCompanyId();

		workEntryCacheModel.accountId = getAccountId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			workEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			workEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			workEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			workEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		workEntryCacheModel.modifiedId = getModifiedId();

		workEntryCacheModel.businessId = getBusinessId();

		Long projectId = getProjectId();

		if (projectId != null) {
			workEntryCacheModel.projectId = projectId;
		}

		Long phaseId = getPhaseId();

		if (phaseId != null) {
			workEntryCacheModel.phaseId = phaseId;
		}

		Long parentId = getParentId();

		if (parentId != null) {
			workEntryCacheModel.parentId = parentId;
		}

		workEntryCacheModel.parentReferenceCode = getParentReferenceCode();

		String parentReferenceCode = workEntryCacheModel.parentReferenceCode;

		if ((parentReferenceCode != null) &&
			(parentReferenceCode.length() == 0)) {

			workEntryCacheModel.parentReferenceCode = null;
		}

		workEntryCacheModel.progress = getProgress();

		workEntryCacheModel.name = getName();

		String name = workEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			workEntryCacheModel.name = null;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			workEntryCacheModel.startDate = startDate.getTime();
		}
		else {
			workEntryCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			workEntryCacheModel.endDate = endDate.getTime();
		}
		else {
			workEntryCacheModel.endDate = Long.MIN_VALUE;
		}

		Date actualStartDate = getActualStartDate();

		if (actualStartDate != null) {
			workEntryCacheModel.actualStartDate = actualStartDate.getTime();
		}
		else {
			workEntryCacheModel.actualStartDate = Long.MIN_VALUE;
		}

		Date actualEndDate = getActualEndDate();

		if (actualEndDate != null) {
			workEntryCacheModel.actualEndDate = actualEndDate.getTime();
		}
		else {
			workEntryCacheModel.actualEndDate = Long.MIN_VALUE;
		}

		workEntryCacheModel.description = getDescription();

		String description = workEntryCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			workEntryCacheModel.description = null;
		}

		workEntryCacheModel.status = getStatus();

		String status = workEntryCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			workEntryCacheModel.status = null;
		}

		workEntryCacheModel.percentage = getPercentage();

		workEntryCacheModel.progressType = getProgressType();

		String progressType = workEntryCacheModel.progressType;

		if ((progressType != null) && (progressType.length() == 0)) {
			workEntryCacheModel.progressType = null;
		}

		workEntryCacheModel.unit = getUnit();

		String unit = workEntryCacheModel.unit;

		if ((unit != null) && (unit.length() == 0)) {
			workEntryCacheModel.unit = null;
		}

		workEntryCacheModel.incompleteAmount = getIncompleteAmount();

		workEntryCacheModel.completeAmount = getCompleteAmount();

		workEntryCacheModel.proportion = getProportion();

		Boolean equalProportions = getEqualProportions();

		if (equalProportions != null) {
			workEntryCacheModel.equalProportions = equalProportions;
		}

		return workEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WorkEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WorkEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WorkEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((WorkEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<WorkEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<WorkEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WorkEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((WorkEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, WorkEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _externalReferenceCode;
	private long _workId;
	private long _groupId;
	private long _companyId;
	private long _accountId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedId;
	private long _businessId;
	private Long _projectId;
	private Long _phaseId;
	private Long _parentId;
	private String _parentReferenceCode;
	private long _progress;
	private String _name;
	private Date _startDate;
	private Date _endDate;
	private Date _actualStartDate;
	private Date _actualEndDate;
	private String _description;
	private String _status;
	private double _percentage;
	private String _progressType;
	private String _unit;
	private double _incompleteAmount;
	private double _completeAmount;
	private long _proportion;
	private Boolean _equalProportions;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<WorkEntry, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((WorkEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put("workId", _workId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("accountId", _accountId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("modifiedId", _modifiedId);
		_columnOriginalValues.put("businessId", _businessId);
		_columnOriginalValues.put("projectId", _projectId);
		_columnOriginalValues.put("phaseId", _phaseId);
		_columnOriginalValues.put("parentId", _parentId);
		_columnOriginalValues.put("parentReferenceCode", _parentReferenceCode);
		_columnOriginalValues.put("progress", _progress);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("endDate", _endDate);
		_columnOriginalValues.put("actualStartDate", _actualStartDate);
		_columnOriginalValues.put("actualEndDate", _actualEndDate);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("percentage", _percentage);
		_columnOriginalValues.put("progressType", _progressType);
		_columnOriginalValues.put("unit", _unit);
		_columnOriginalValues.put("incompleteAmount", _incompleteAmount);
		_columnOriginalValues.put("completeAmount", _completeAmount);
		_columnOriginalValues.put("proportion", _proportion);
		_columnOriginalValues.put("equalProportions", _equalProportions);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("externalReferenceCode", 2L);

		columnBitmasks.put("workId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("accountId", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("modifiedId", 256L);

		columnBitmasks.put("businessId", 512L);

		columnBitmasks.put("projectId", 1024L);

		columnBitmasks.put("phaseId", 2048L);

		columnBitmasks.put("parentId", 4096L);

		columnBitmasks.put("parentReferenceCode", 8192L);

		columnBitmasks.put("progress", 16384L);

		columnBitmasks.put("name", 32768L);

		columnBitmasks.put("startDate", 65536L);

		columnBitmasks.put("endDate", 131072L);

		columnBitmasks.put("actualStartDate", 262144L);

		columnBitmasks.put("actualEndDate", 524288L);

		columnBitmasks.put("description", 1048576L);

		columnBitmasks.put("status", 2097152L);

		columnBitmasks.put("percentage", 4194304L);

		columnBitmasks.put("progressType", 8388608L);

		columnBitmasks.put("unit", 16777216L);

		columnBitmasks.put("incompleteAmount", 33554432L);

		columnBitmasks.put("completeAmount", 67108864L);

		columnBitmasks.put("proportion", 134217728L);

		columnBitmasks.put("equalProportions", 268435456L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private WorkEntry _escapedModel;

}