apiDir: "../common-file-rest-api/src/main/java"
apiPackagePath: "com.swork.common.file.rest"
application:
    baseURI: "/common-file-rest"
    className: "CommonFileRestApplication"
    name: "CommonFileRest"
author: "ninhvv"
clientDir: "../common-file-rest-client/src/main/java"
testDir: "../common-file-rest-test/src/testIntegration/java"