apiDir: "../common-file-rest-api/src/main/java"
apiPackagePath: "com.swork.common.file.rest"
application:
    baseURI: "/swork/common-file-rest"
    className: "CommonFileRestApplication"
    name: "CommonFileRest"
author: "longnv"
