components:
  schemas:
    Account:
      description: Account model
      properties:
        id:
          format: int64
          readOnly: true
          type: integer
        externalReferenceCode:
          type: string
          readOnly: true
        createDate:
          type: string
          format: date
          readOnly: true
        username:
          type: string
        fullName:
          type: string
        dateOfBirth:
          type: string
          format: date
        email:
          type: string
        phoneNumber:
          type: string
        address:
          type: string
        status:
          enum: [ active, inactive ]
    ChangePassword:
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string
        newPasswordRepeat:
          type: string
    ResetPassword:
      properties:
        username:
          type: string
        email:
          type: string
info:
  description: "AccountRest REST API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  title: "AccountRest"
  version: v1.0
openapi: 3.0.1
paths:
  "/accounts":
    get:
      tags: [ "Account" ]
      description:
        Retrieves the account. Results can be paginated, filtered, searched, and sorted.
      operationId: getAccountsPage
      parameters:
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: search
          schema:
            type: string
        - in: query
          name: sort
          schema:
            type: string
      responses:
        200:
          description: The data returned
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Account"
                type: array
            application/xml:
              schema:
                items:
                  $ref: "#/components/schemas/Account"
                type: array
    post:
      tags: [ "Account" ]
      description: Create a new Account
      operationId: postAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
          application/xml:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        201:
          description:
            "Created an Account"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
            application/xml:
              schema:
                $ref: "#/components/schemas/Account"
  "/accounts/{accountId}":
    put:
      tags: [ "Account" ]
      description: Update an Account
      operationId: putAccount
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
          application/xml:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        200:
          description:
            "Updated an Account"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
            application/xml:
              schema:
                $ref: "#/components/schemas/Account"
    get:
      tags: [ "Account" ]
      description: Get an Account
      operationId: getAccount
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          description:
            "Get detail an Account"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
            application/xml:
              schema:
                $ref: "#/components/schemas/Account"
    delete:
      tags: [ "Account" ]
      description: Delete an account
      operationId: deleteAccount
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            format: int64
            type: integer
      responses:
        204:
          description:
            "Deleted an Account"
          content:
            application/json: { }
            application/xml: { }
  "/accounts/approval/{accountId}":
    put:
      tags: [ "Account" ]
      description: Update an Account
      operationId: approvalAccount
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            format: int64
            type: integer
        - in: query
          name: status
          required: true
          schema:
            type: string
            enum: [ active, inactive ]
      responses:
        204:
          description:
            "Updated an Account"
          content:
            application/json: { }
            application/xml: { }
  "/accounts/account-info":
    get:
      tags: [ "Account" ]
      description: Update an Account
      operationId: getAccountInfo
      responses:
        200:
          description:
            "Get detail an Account"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
            application/xml:
              schema:
                $ref: "#/components/schemas/Account"
    put:
      tags: [ "Account" ]
      description: "Update Account Info"
      operationId: putAccountInfo
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
          application/xml:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        204:
          description:
            "Get Current Account Info"
          content:
            application/json: { }
            application/xml: { }
    patch:
      tags: [ "Account" ]
      description: "Update Account Info"
      operationId: patchAccountPassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePassword'
          application/xml:
            schema:
              $ref: '#/components/schemas/ChangePassword'
      responses:
        204:
          description:
            "Change Password"
          content:
            application/json: { }
            application/xml: { }
  "/accounts/reset-password":
    patch:
      tags: [ "Account" ]
      description: "Update Account Info"
      operationId: resetPassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPassword'
          application/xml:
            schema:
              $ref: '#/components/schemas/ResetPassword'
      responses:
        204:
          description:
            "Change Password"
          content:
            application/json: { }
            application/xml: { }