/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.account.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AccountEntry service. Represents a row in the &quot;SW_AccountEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.swork.account.service.model.impl.AccountEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.swork.account.service.model.impl.AccountEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AccountEntry
 * @generated
 */
@ProviderType
public interface AccountEntryModel
	extends BaseModel<AccountEntry>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a account entry model instance should use the {@link AccountEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this account entry.
	 *
	 * @return the primary key of this account entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this account entry.
	 *
	 * @param primaryKey the primary key of this account entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this account entry.
	 *
	 * @return the uuid of this account entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this account entry.
	 *
	 * @param uuid the uuid of this account entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this account entry.
	 *
	 * @return the external reference code of this account entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this account entry.
	 *
	 * @param externalReferenceCode the external reference code of this account entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the account ID of this account entry.
	 *
	 * @return the account ID of this account entry
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this account entry.
	 *
	 * @param accountId the account ID of this account entry
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the group ID of this account entry.
	 *
	 * @return the group ID of this account entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this account entry.
	 *
	 * @param groupId the group ID of this account entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this account entry.
	 *
	 * @return the company ID of this account entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this account entry.
	 *
	 * @param companyId the company ID of this account entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this account entry.
	 *
	 * @return the create date of this account entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this account entry.
	 *
	 * @param createDate the create date of this account entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this account entry.
	 *
	 * @return the modified date of this account entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this account entry.
	 *
	 * @param modifiedDate the modified date of this account entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the creator ID of this account entry.
	 *
	 * @return the creator ID of this account entry
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this account entry.
	 *
	 * @param creatorId the creator ID of this account entry
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the username of this account entry.
	 *
	 * @return the username of this account entry
	 */
	@AutoEscape
	public String getUsername();

	/**
	 * Sets the username of this account entry.
	 *
	 * @param username the username of this account entry
	 */
	public void setUsername(String username);

	/**
	 * Returns the password of this account entry.
	 *
	 * @return the password of this account entry
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this account entry.
	 *
	 * @param password the password of this account entry
	 */
	public void setPassword(String password);

	/**
	 * Returns the full name of this account entry.
	 *
	 * @return the full name of this account entry
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this account entry.
	 *
	 * @param fullName the full name of this account entry
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the phone number of this account entry.
	 *
	 * @return the phone number of this account entry
	 */
	public Integer getPhoneNumber();

	/**
	 * Sets the phone number of this account entry.
	 *
	 * @param phoneNumber the phone number of this account entry
	 */
	public void setPhoneNumber(Integer phoneNumber);

	/**
	 * Returns the email of this account entry.
	 *
	 * @return the email of this account entry
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this account entry.
	 *
	 * @param email the email of this account entry
	 */
	public void setEmail(String email);

	/**
	 * Returns the address of this account entry.
	 *
	 * @return the address of this account entry
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this account entry.
	 *
	 * @param address the address of this account entry
	 */
	public void setAddress(String address);

	/**
	 * Returns the department ID of this account entry.
	 *
	 * @return the department ID of this account entry
	 */
	public Long getDepartmentId();

	/**
	 * Sets the department ID of this account entry.
	 *
	 * @param departmentId the department ID of this account entry
	 */
	public void setDepartmentId(Long departmentId);

	/**
	 * Returns the business ID of this account entry.
	 *
	 * @return the business ID of this account entry
	 */
	public Long getBusinessId();

	/**
	 * Sets the business ID of this account entry.
	 *
	 * @param businessId the business ID of this account entry
	 */
	public void setBusinessId(Long businessId);

	@Override
	public AccountEntry cloneWithOriginalValues();

}