/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.account.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AccountPermissionEntry service. Represents a row in the &quot;SW_AccountPermission&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.swork.account.service.model.impl.AccountPermissionEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.swork.account.service.model.impl.AccountPermissionEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AccountPermissionEntry
 * @generated
 */
@ProviderType
public interface AccountPermissionEntryModel
	extends BaseModel<AccountPermissionEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a account permission entry model instance should use the {@link AccountPermissionEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this account permission entry.
	 *
	 * @return the primary key of this account permission entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this account permission entry.
	 *
	 * @param primaryKey the primary key of this account permission entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this account permission entry.
	 *
	 * @return the uuid of this account permission entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this account permission entry.
	 *
	 * @param uuid the uuid of this account permission entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this account permission entry.
	 *
	 * @return the external reference code of this account permission entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this account permission entry.
	 *
	 * @param externalReferenceCode the external reference code of this account permission entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the ID of this account permission entry.
	 *
	 * @return the ID of this account permission entry
	 */
	public long getId();

	/**
	 * Sets the ID of this account permission entry.
	 *
	 * @param id the ID of this account permission entry
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this account permission entry.
	 *
	 * @return the company ID of this account permission entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this account permission entry.
	 *
	 * @param companyId the company ID of this account permission entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the permission ID of this account permission entry.
	 *
	 * @return the permission ID of this account permission entry
	 */
	public long getPermissionId();

	/**
	 * Sets the permission ID of this account permission entry.
	 *
	 * @param permissionId the permission ID of this account permission entry
	 */
	public void setPermissionId(long permissionId);

	/**
	 * Returns the account ID of this account permission entry.
	 *
	 * @return the account ID of this account permission entry
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this account permission entry.
	 *
	 * @param accountId the account ID of this account permission entry
	 */
	public void setAccountId(long accountId);

	@Override
	public AccountPermissionEntry cloneWithOriginalValues();

}