/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.account.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PermisionEntry service. Represents a row in the &quot;SW_Permision&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.swork.account.service.model.impl.PermisionEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.swork.account.service.model.impl.PermisionEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PermisionEntry
 * @generated
 */
@ProviderType
public interface PermisionEntryModel
	extends BaseModel<PermisionEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a permision entry model instance should use the {@link PermisionEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this permision entry.
	 *
	 * @return the primary key of this permision entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this permision entry.
	 *
	 * @param primaryKey the primary key of this permision entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this permision entry.
	 *
	 * @return the uuid of this permision entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this permision entry.
	 *
	 * @param uuid the uuid of this permision entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this permision entry.
	 *
	 * @return the external reference code of this permision entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this permision entry.
	 *
	 * @param externalReferenceCode the external reference code of this permision entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the ID of this permision entry.
	 *
	 * @return the ID of this permision entry
	 */
	public long getId();

	/**
	 * Sets the ID of this permision entry.
	 *
	 * @param id the ID of this permision entry
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this permision entry.
	 *
	 * @return the company ID of this permision entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this permision entry.
	 *
	 * @param companyId the company ID of this permision entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this permision entry.
	 *
	 * @return the name of this permision entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this permision entry.
	 *
	 * @param name the name of this permision entry
	 */
	public void setName(String name);

	@Override
	public PermisionEntry cloneWithOriginalValues();

}