/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.checklist.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ChecklistHandlerEntry service. Represents a row in the &quot;SW_ChecklistHandler&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.swork.checklist.service.model.impl.ChecklistHandlerEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.swork.checklist.service.model.impl.ChecklistHandlerEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChecklistHandlerEntry
 * @generated
 */
@ProviderType
public interface ChecklistHandlerEntryModel
	extends BaseModel<ChecklistHandlerEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a checklist handler entry model instance should use the {@link ChecklistHandlerEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this checklist handler entry.
	 *
	 * @return the primary key of this checklist handler entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this checklist handler entry.
	 *
	 * @param primaryKey the primary key of this checklist handler entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this checklist handler entry.
	 *
	 * @return the uuid of this checklist handler entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this checklist handler entry.
	 *
	 * @param uuid the uuid of this checklist handler entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the checklist handler ID of this checklist handler entry.
	 *
	 * @return the checklist handler ID of this checklist handler entry
	 */
	public long getChecklistHandlerId();

	/**
	 * Sets the checklist handler ID of this checklist handler entry.
	 *
	 * @param checklistHandlerId the checklist handler ID of this checklist handler entry
	 */
	public void setChecklistHandlerId(long checklistHandlerId);

	/**
	 * Returns the group ID of this checklist handler entry.
	 *
	 * @return the group ID of this checklist handler entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this checklist handler entry.
	 *
	 * @param groupId the group ID of this checklist handler entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the check list ID of this checklist handler entry.
	 *
	 * @return the check list ID of this checklist handler entry
	 */
	public Long getCheckListId();

	/**
	 * Sets the check list ID of this checklist handler entry.
	 *
	 * @param checkListId the check list ID of this checklist handler entry
	 */
	public void setCheckListId(Long checkListId);

	/**
	 * Returns the acc ID of this checklist handler entry.
	 *
	 * @return the acc ID of this checklist handler entry
	 */
	public Long getAccId();

	/**
	 * Sets the acc ID of this checklist handler entry.
	 *
	 * @param accId the acc ID of this checklist handler entry
	 */
	public void setAccId(Long accId);

	@Override
	public ChecklistHandlerEntry cloneWithOriginalValues();

}