/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.checklist.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ChecklistEntry service. Represents a row in the &quot;SW_Checklist&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.swork.checklist.service.model.impl.ChecklistEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.swork.checklist.service.model.impl.ChecklistEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChecklistEntry
 * @generated
 */
@ProviderType
public interface ChecklistEntryModel
	extends BaseModel<ChecklistEntry>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a checklist entry model instance should use the {@link ChecklistEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this checklist entry.
	 *
	 * @return the primary key of this checklist entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this checklist entry.
	 *
	 * @param primaryKey the primary key of this checklist entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this checklist entry.
	 *
	 * @return the uuid of this checklist entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this checklist entry.
	 *
	 * @param uuid the uuid of this checklist entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the checklist ID of this checklist entry.
	 *
	 * @return the checklist ID of this checklist entry
	 */
	public long getChecklistId();

	/**
	 * Sets the checklist ID of this checklist entry.
	 *
	 * @param checklistId the checklist ID of this checklist entry
	 */
	public void setChecklistId(long checklistId);

	/**
	 * Returns the group ID of this checklist entry.
	 *
	 * @return the group ID of this checklist entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this checklist entry.
	 *
	 * @param groupId the group ID of this checklist entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this checklist entry.
	 *
	 * @return the company ID of this checklist entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this checklist entry.
	 *
	 * @param companyId the company ID of this checklist entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this checklist entry.
	 *
	 * @return the user ID of this checklist entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this checklist entry.
	 *
	 * @param userId the user ID of this checklist entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this checklist entry.
	 *
	 * @return the user uuid of this checklist entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this checklist entry.
	 *
	 * @param userUuid the user uuid of this checklist entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this checklist entry.
	 *
	 * @return the user name of this checklist entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this checklist entry.
	 *
	 * @param userName the user name of this checklist entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this checklist entry.
	 *
	 * @return the create date of this checklist entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this checklist entry.
	 *
	 * @param createDate the create date of this checklist entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this checklist entry.
	 *
	 * @return the modified date of this checklist entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this checklist entry.
	 *
	 * @param modifiedDate the modified date of this checklist entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this checklist entry.
	 *
	 * @return the name of this checklist entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this checklist entry.
	 *
	 * @param name the name of this checklist entry
	 */
	public void setName(String name);

	/**
	 * Returns the start date of this checklist entry.
	 *
	 * @return the start date of this checklist entry
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this checklist entry.
	 *
	 * @param startDate the start date of this checklist entry
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this checklist entry.
	 *
	 * @return the end date of this checklist entry
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this checklist entry.
	 *
	 * @param endDate the end date of this checklist entry
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the task ID of this checklist entry.
	 *
	 * @return the task ID of this checklist entry
	 */
	public Long getTaskId();

	/**
	 * Sets the task ID of this checklist entry.
	 *
	 * @param taskId the task ID of this checklist entry
	 */
	public void setTaskId(Long taskId);

	/**
	 * Returns the status of this checklist entry.
	 *
	 * @return the status of this checklist entry
	 */
	public Boolean getStatus();

	/**
	 * Sets the status of this checklist entry.
	 *
	 * @param status the status of this checklist entry
	 */
	public void setStatus(Boolean status);

	@Override
	public ChecklistEntry cloneWithOriginalValues();

}