/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.checklist.service.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.swork.checklist.service.model.ChecklistHandlerEntry;
import com.swork.checklist.service.service.ChecklistHandlerEntryLocalService;
import com.swork.checklist.service.service.ChecklistHandlerEntryLocalServiceUtil;
import com.swork.checklist.service.service.persistence.ChecklistEntryPersistence;
import com.swork.checklist.service.service.persistence.ChecklistHandlerEntryPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the checklist handler entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.swork.checklist.service.service.impl.ChecklistHandlerEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.swork.checklist.service.service.impl.ChecklistHandlerEntryLocalServiceImpl
 * @generated
 */
public abstract class ChecklistHandlerEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, ChecklistHandlerEntryLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ChecklistHandlerEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ChecklistHandlerEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the checklist handler entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ChecklistHandlerEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param checklistHandlerEntry the checklist handler entry
	 * @return the checklist handler entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ChecklistHandlerEntry addChecklistHandlerEntry(
		ChecklistHandlerEntry checklistHandlerEntry) {

		checklistHandlerEntry.setNew(true);

		return checklistHandlerEntryPersistence.update(checklistHandlerEntry);
	}

	/**
	 * Creates a new checklist handler entry with the primary key. Does not add the checklist handler entry to the database.
	 *
	 * @param checklistHandlerId the primary key for the new checklist handler entry
	 * @return the new checklist handler entry
	 */
	@Override
	@Transactional(enabled = false)
	public ChecklistHandlerEntry createChecklistHandlerEntry(
		long checklistHandlerId) {

		return checklistHandlerEntryPersistence.create(checklistHandlerId);
	}

	/**
	 * Deletes the checklist handler entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ChecklistHandlerEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param checklistHandlerId the primary key of the checklist handler entry
	 * @return the checklist handler entry that was removed
	 * @throws PortalException if a checklist handler entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ChecklistHandlerEntry deleteChecklistHandlerEntry(
			long checklistHandlerId)
		throws PortalException {

		return checklistHandlerEntryPersistence.remove(checklistHandlerId);
	}

	/**
	 * Deletes the checklist handler entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ChecklistHandlerEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param checklistHandlerEntry the checklist handler entry
	 * @return the checklist handler entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ChecklistHandlerEntry deleteChecklistHandlerEntry(
		ChecklistHandlerEntry checklistHandlerEntry) {

		return checklistHandlerEntryPersistence.remove(checklistHandlerEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return checklistHandlerEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ChecklistHandlerEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return checklistHandlerEntryPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.swork.checklist.service.model.impl.ChecklistHandlerEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return checklistHandlerEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.swork.checklist.service.model.impl.ChecklistHandlerEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return checklistHandlerEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return checklistHandlerEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return checklistHandlerEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ChecklistHandlerEntry fetchChecklistHandlerEntry(
		long checklistHandlerId) {

		return checklistHandlerEntryPersistence.fetchByPrimaryKey(
			checklistHandlerId);
	}

	/**
	 * Returns the checklist handler entry matching the UUID and group.
	 *
	 * @param uuid the checklist handler entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching checklist handler entry, or <code>null</code> if a matching checklist handler entry could not be found
	 */
	@Override
	public ChecklistHandlerEntry fetchChecklistHandlerEntryByUuidAndGroupId(
		String uuid, long groupId) {

		return checklistHandlerEntryPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the checklist handler entry with the primary key.
	 *
	 * @param checklistHandlerId the primary key of the checklist handler entry
	 * @return the checklist handler entry
	 * @throws PortalException if a checklist handler entry with the primary key could not be found
	 */
	@Override
	public ChecklistHandlerEntry getChecklistHandlerEntry(
			long checklistHandlerId)
		throws PortalException {

		return checklistHandlerEntryPersistence.findByPrimaryKey(
			checklistHandlerId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			checklistHandlerEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ChecklistHandlerEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("checklistHandlerId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			checklistHandlerEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			ChecklistHandlerEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"checklistHandlerId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			checklistHandlerEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ChecklistHandlerEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("checklistHandlerId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return checklistHandlerEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return checklistHandlerEntryLocalService.deleteChecklistHandlerEntry(
			(ChecklistHandlerEntry)persistedModel);
	}

	@Override
	public BasePersistence<ChecklistHandlerEntry> getBasePersistence() {
		return checklistHandlerEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return checklistHandlerEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the checklist handler entry matching the UUID and group.
	 *
	 * @param uuid the checklist handler entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching checklist handler entry
	 * @throws PortalException if a matching checklist handler entry could not be found
	 */
	@Override
	public ChecklistHandlerEntry getChecklistHandlerEntryByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return checklistHandlerEntryPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the checklist handler entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.swork.checklist.service.model.impl.ChecklistHandlerEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of checklist handler entries
	 * @param end the upper bound of the range of checklist handler entries (not inclusive)
	 * @return the range of checklist handler entries
	 */
	@Override
	public List<ChecklistHandlerEntry> getChecklistHandlerEntries(
		int start, int end) {

		return checklistHandlerEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of checklist handler entries.
	 *
	 * @return the number of checklist handler entries
	 */
	@Override
	public int getChecklistHandlerEntriesCount() {
		return checklistHandlerEntryPersistence.countAll();
	}

	/**
	 * Updates the checklist handler entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ChecklistHandlerEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param checklistHandlerEntry the checklist handler entry
	 * @return the checklist handler entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ChecklistHandlerEntry updateChecklistHandlerEntry(
		ChecklistHandlerEntry checklistHandlerEntry) {

		return checklistHandlerEntryPersistence.update(checklistHandlerEntry);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ChecklistHandlerEntryLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		checklistHandlerEntryLocalService =
			(ChecklistHandlerEntryLocalService)aopProxy;

		_setLocalServiceUtilService(checklistHandlerEntryLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ChecklistHandlerEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ChecklistHandlerEntry.class;
	}

	protected String getModelClassName() {
		return ChecklistHandlerEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				checklistHandlerEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		ChecklistHandlerEntryLocalService checklistHandlerEntryLocalService) {

		try {
			Field field =
				ChecklistHandlerEntryLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, checklistHandlerEntryLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected ChecklistEntryPersistence checklistEntryPersistence;

	protected ChecklistHandlerEntryLocalService
		checklistHandlerEntryLocalService;

	@Reference
	protected ChecklistHandlerEntryPersistence checklistHandlerEntryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}