/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.core.resource.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ResourceEntry service. Represents a row in the &quot;SW_Resource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.swork.core.resource.service.model.impl.ResourceEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.swork.core.resource.service.model.impl.ResourceEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ResourceEntry
 * @generated
 */
@ProviderType
public interface ResourceEntryModel
	extends BaseModel<ResourceEntry>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a resource entry model instance should use the {@link ResourceEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this resource entry.
	 *
	 * @return the primary key of this resource entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this resource entry.
	 *
	 * @param primaryKey the primary key of this resource entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this resource entry.
	 *
	 * @return the uuid of this resource entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this resource entry.
	 *
	 * @param uuid the uuid of this resource entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this resource entry.
	 *
	 * @return the external reference code of this resource entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this resource entry.
	 *
	 * @param externalReferenceCode the external reference code of this resource entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the resource ID of this resource entry.
	 *
	 * @return the resource ID of this resource entry
	 */
	public long getResourceId();

	/**
	 * Sets the resource ID of this resource entry.
	 *
	 * @param resourceId the resource ID of this resource entry
	 */
	public void setResourceId(long resourceId);

	/**
	 * Returns the group ID of this resource entry.
	 *
	 * @return the group ID of this resource entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this resource entry.
	 *
	 * @param groupId the group ID of this resource entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this resource entry.
	 *
	 * @return the company ID of this resource entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this resource entry.
	 *
	 * @param companyId the company ID of this resource entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the account ID of this resource entry.
	 *
	 * @return the account ID of this resource entry
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this resource entry.
	 *
	 * @param accountId the account ID of this resource entry
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the create date of this resource entry.
	 *
	 * @return the create date of this resource entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this resource entry.
	 *
	 * @param createDate the create date of this resource entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this resource entry.
	 *
	 * @return the modified date of this resource entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this resource entry.
	 *
	 * @param modifiedDate the modified date of this resource entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the business ID of this resource entry.
	 *
	 * @return the business ID of this resource entry
	 */
	public long getBusinessId();

	/**
	 * Sets the business ID of this resource entry.
	 *
	 * @param businessId the business ID of this resource entry
	 */
	public void setBusinessId(long businessId);

	/**
	 * Returns the modified ID of this resource entry.
	 *
	 * @return the modified ID of this resource entry
	 */
	public long getModifiedId();

	/**
	 * Sets the modified ID of this resource entry.
	 *
	 * @param modifiedId the modified ID of this resource entry
	 */
	public void setModifiedId(long modifiedId);

	/**
	 * Returns the work ID of this resource entry.
	 *
	 * @return the work ID of this resource entry
	 */
	public Long getWorkId();

	/**
	 * Sets the work ID of this resource entry.
	 *
	 * @param workId the work ID of this resource entry
	 */
	public void setWorkId(Long workId);

	/**
	 * Returns the phase ID of this resource entry.
	 *
	 * @return the phase ID of this resource entry
	 */
	public Long getPhaseId();

	/**
	 * Sets the phase ID of this resource entry.
	 *
	 * @param phaseId the phase ID of this resource entry
	 */
	public void setPhaseId(Long phaseId);

	/**
	 * Returns the project ID of this resource entry.
	 *
	 * @return the project ID of this resource entry
	 */
	public Long getProjectId();

	/**
	 * Sets the project ID of this resource entry.
	 *
	 * @param projectId the project ID of this resource entry
	 */
	public void setProjectId(Long projectId);

	/**
	 * Returns the resource type ID of this resource entry.
	 *
	 * @return the resource type ID of this resource entry
	 */
	public long getResourceTypeId();

	/**
	 * Sets the resource type ID of this resource entry.
	 *
	 * @param resourceTypeId the resource type ID of this resource entry
	 */
	public void setResourceTypeId(long resourceTypeId);

	/**
	 * Returns the resource type name of this resource entry.
	 *
	 * @return the resource type name of this resource entry
	 */
	@AutoEscape
	public String getResourceTypeName();

	/**
	 * Sets the resource type name of this resource entry.
	 *
	 * @param resourceTypeName the resource type name of this resource entry
	 */
	public void setResourceTypeName(String resourceTypeName);

	/**
	 * Returns the team ID of this resource entry.
	 *
	 * @return the team ID of this resource entry
	 */
	public long getTeamId();

	/**
	 * Sets the team ID of this resource entry.
	 *
	 * @param teamId the team ID of this resource entry
	 */
	public void setTeamId(long teamId);

	/**
	 * Returns the team name of this resource entry.
	 *
	 * @return the team name of this resource entry
	 */
	@AutoEscape
	public String getTeamName();

	/**
	 * Sets the team name of this resource entry.
	 *
	 * @param teamName the team name of this resource entry
	 */
	public void setTeamName(String teamName);

	/**
	 * Returns the quantity of this resource entry.
	 *
	 * @return the quantity of this resource entry
	 */
	public long getQuantity();

	/**
	 * Sets the quantity of this resource entry.
	 *
	 * @param quantity the quantity of this resource entry
	 */
	public void setQuantity(long quantity);

	/**
	 * Returns the unit of this resource entry.
	 *
	 * @return the unit of this resource entry
	 */
	@AutoEscape
	public String getUnit();

	/**
	 * Sets the unit of this resource entry.
	 *
	 * @param unit the unit of this resource entry
	 */
	public void setUnit(String unit);

	/**
	 * Returns the date resource of this resource entry.
	 *
	 * @return the date resource of this resource entry
	 */
	public Date getDateResource();

	/**
	 * Sets the date resource of this resource entry.
	 *
	 * @param dateResource the date resource of this resource entry
	 */
	public void setDateResource(Date dateResource);

	/**
	 * Returns the total amount of this resource entry.
	 *
	 * @return the total amount of this resource entry
	 */
	public Long getTotalAmount();

	/**
	 * Sets the total amount of this resource entry.
	 *
	 * @param totalAmount the total amount of this resource entry
	 */
	public void setTotalAmount(Long totalAmount);

	@Override
	public ResourceEntry cloneWithOriginalValues();

}