/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.core.resource.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TeamEntry service. Represents a row in the &quot;SW_Team&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.swork.core.resource.service.model.impl.TeamEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.swork.core.resource.service.model.impl.TeamEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TeamEntry
 * @generated
 */
@ProviderType
public interface TeamEntryModel
	extends BaseModel<TeamEntry>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a team entry model instance should use the {@link TeamEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this team entry.
	 *
	 * @return the primary key of this team entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this team entry.
	 *
	 * @param primaryKey the primary key of this team entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this team entry.
	 *
	 * @return the uuid of this team entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this team entry.
	 *
	 * @param uuid the uuid of this team entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this team entry.
	 *
	 * @return the external reference code of this team entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this team entry.
	 *
	 * @param externalReferenceCode the external reference code of this team entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the team ID of this team entry.
	 *
	 * @return the team ID of this team entry
	 */
	public long getTeamId();

	/**
	 * Sets the team ID of this team entry.
	 *
	 * @param teamId the team ID of this team entry
	 */
	public void setTeamId(long teamId);

	/**
	 * Returns the group ID of this team entry.
	 *
	 * @return the group ID of this team entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this team entry.
	 *
	 * @param groupId the group ID of this team entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this team entry.
	 *
	 * @return the company ID of this team entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this team entry.
	 *
	 * @param companyId the company ID of this team entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the account ID of this team entry.
	 *
	 * @return the account ID of this team entry
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this team entry.
	 *
	 * @param accountId the account ID of this team entry
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the create date of this team entry.
	 *
	 * @return the create date of this team entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this team entry.
	 *
	 * @param createDate the create date of this team entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this team entry.
	 *
	 * @return the modified date of this team entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this team entry.
	 *
	 * @param modifiedDate the modified date of this team entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the business ID of this team entry.
	 *
	 * @return the business ID of this team entry
	 */
	public long getBusinessId();

	/**
	 * Sets the business ID of this team entry.
	 *
	 * @param businessId the business ID of this team entry
	 */
	public void setBusinessId(long businessId);

	/**
	 * Returns the modified ID of this team entry.
	 *
	 * @return the modified ID of this team entry
	 */
	public long getModifiedId();

	/**
	 * Sets the modified ID of this team entry.
	 *
	 * @param modifiedId the modified ID of this team entry
	 */
	public void setModifiedId(long modifiedId);

	/**
	 * Returns the name of this team entry.
	 *
	 * @return the name of this team entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this team entry.
	 *
	 * @param name the name of this team entry
	 */
	public void setName(String name);

	/**
	 * Returns the description of this team entry.
	 *
	 * @return the description of this team entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this team entry.
	 *
	 * @param description the description of this team entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the is active of this team entry.
	 *
	 * @return the is active of this team entry
	 */
	public Boolean getIsActive();

	/**
	 * Sets the is active of this team entry.
	 *
	 * @param isActive the is active of this team entry
	 */
	public void setIsActive(Boolean isActive);

	/**
	 * Returns the phase ID of this team entry.
	 *
	 * @return the phase ID of this team entry
	 */
	public Long getPhaseId();

	/**
	 * Sets the phase ID of this team entry.
	 *
	 * @param phaseId the phase ID of this team entry
	 */
	public void setPhaseId(Long phaseId);

	/**
	 * Returns the project ID of this team entry.
	 *
	 * @return the project ID of this team entry
	 */
	public Long getProjectId();

	/**
	 * Sets the project ID of this team entry.
	 *
	 * @param projectId the project ID of this team entry
	 */
	public void setProjectId(Long projectId);

	/**
	 * Returns the total incoming of this team entry.
	 *
	 * @return the total incoming of this team entry
	 */
	public Long getTotalIncoming();

	/**
	 * Sets the total incoming of this team entry.
	 *
	 * @param totalIncoming the total incoming of this team entry
	 */
	public void setTotalIncoming(Long totalIncoming);

	/**
	 * Returns the total spending of this team entry.
	 *
	 * @return the total spending of this team entry
	 */
	public Long getTotalSpending();

	/**
	 * Sets the total spending of this team entry.
	 *
	 * @param totalSpending the total spending of this team entry
	 */
	public void setTotalSpending(Long totalSpending);

	@Override
	public TeamEntry cloneWithOriginalValues();

}