/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.auth.login.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TokenEntry service. Represents a row in the &quot;SW_TokenEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.swork.auth.login.service.model.impl.TokenEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.swork.auth.login.service.model.impl.TokenEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TokenEntry
 * @generated
 */
@ProviderType
public interface TokenEntryModel extends BaseModel<TokenEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a token entry model instance should use the {@link TokenEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this token entry.
	 *
	 * @return the primary key of this token entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this token entry.
	 *
	 * @param primaryKey the primary key of this token entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this token entry.
	 *
	 * @return the uuid of this token entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this token entry.
	 *
	 * @param uuid the uuid of this token entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the token ID of this token entry.
	 *
	 * @return the token ID of this token entry
	 */
	public long getTokenId();

	/**
	 * Sets the token ID of this token entry.
	 *
	 * @param tokenId the token ID of this token entry
	 */
	public void setTokenId(long tokenId);

	/**
	 * Returns the account ID of this token entry.
	 *
	 * @return the account ID of this token entry
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this token entry.
	 *
	 * @param accountId the account ID of this token entry
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the business ID of this token entry.
	 *
	 * @return the business ID of this token entry
	 */
	public long getBusinessId();

	/**
	 * Sets the business ID of this token entry.
	 *
	 * @param businessId the business ID of this token entry
	 */
	public void setBusinessId(long businessId);

	/**
	 * Returns the user name of this token entry.
	 *
	 * @return the user name of this token entry
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this token entry.
	 *
	 * @param userName the user name of this token entry
	 */
	public void setUserName(String userName);

	/**
	 * Returns the refresh token of this token entry.
	 *
	 * @return the refresh token of this token entry
	 */
	@AutoEscape
	public String getRefreshToken();

	/**
	 * Sets the refresh token of this token entry.
	 *
	 * @param refreshToken the refresh token of this token entry
	 */
	public void setRefreshToken(String refreshToken);

	/**
	 * Returns the expiry date of this token entry.
	 *
	 * @return the expiry date of this token entry
	 */
	public Date getExpiryDate();

	/**
	 * Sets the expiry date of this token entry.
	 *
	 * @param expiryDate the expiry date of this token entry
	 */
	public void setExpiryDate(Date expiryDate);

	/**
	 * Returns the issued date of this token entry.
	 *
	 * @return the issued date of this token entry
	 */
	public Date getIssuedDate();

	/**
	 * Sets the issued date of this token entry.
	 *
	 * @param issuedDate the issued date of this token entry
	 */
	public void setIssuedDate(Date issuedDate);

	/**
	 * Returns the refreshed date of this token entry.
	 *
	 * @return the refreshed date of this token entry
	 */
	public Date getRefreshedDate();

	/**
	 * Sets the refreshed date of this token entry.
	 *
	 * @param refreshedDate the refreshed date of this token entry
	 */
	public void setRefreshedDate(Date refreshedDate);

	/**
	 * Returns the user agent of this token entry.
	 *
	 * @return the user agent of this token entry
	 */
	@AutoEscape
	public String getUserAgent();

	/**
	 * Sets the user agent of this token entry.
	 *
	 * @param userAgent the user agent of this token entry
	 */
	public void setUserAgent(String userAgent);

	/**
	 * Returns the client ip of this token entry.
	 *
	 * @return the client ip of this token entry
	 */
	@AutoEscape
	public String getClientIp();

	/**
	 * Sets the client ip of this token entry.
	 *
	 * @param clientIp the client ip of this token entry
	 */
	public void setClientIp(String clientIp);

	/**
	 * Returns the first login date of this token entry.
	 *
	 * @return the first login date of this token entry
	 */
	public Date getFirstLoginDate();

	/**
	 * Sets the first login date of this token entry.
	 *
	 * @param firstLoginDate the first login date of this token entry
	 */
	public void setFirstLoginDate(Date firstLoginDate);

	/**
	 * Returns the session ID of this token entry.
	 *
	 * @return the session ID of this token entry
	 */
	@AutoEscape
	public String getSessionId();

	/**
	 * Sets the session ID of this token entry.
	 *
	 * @param sessionId the session ID of this token entry
	 */
	public void setSessionId(String sessionId);

	/**
	 * Returns the remember of this token entry.
	 *
	 * @return the remember of this token entry
	 */
	public Boolean getRemember();

	/**
	 * Sets the remember of this token entry.
	 *
	 * @param remember the remember of this token entry
	 */
	public void setRemember(Boolean remember);

	@Override
	public TokenEntry cloneWithOriginalValues();

}