/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.common.file.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FileManagerEntry service. Represents a row in the &quot;SW_FileManager&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.swork.common.file.model.impl.FileManagerEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.swork.common.file.model.impl.FileManagerEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FileManagerEntry
 * @generated
 */
@ProviderType
public interface FileManagerEntryModel
	extends BaseModel<FileManagerEntry>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a file manager entry model instance should use the {@link FileManagerEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this file manager entry.
	 *
	 * @return the primary key of this file manager entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this file manager entry.
	 *
	 * @param primaryKey the primary key of this file manager entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this file manager entry.
	 *
	 * @return the uuid of this file manager entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this file manager entry.
	 *
	 * @param uuid the uuid of this file manager entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this file manager entry.
	 *
	 * @return the external reference code of this file manager entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this file manager entry.
	 *
	 * @param externalReferenceCode the external reference code of this file manager entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the ID of this file manager entry.
	 *
	 * @return the ID of this file manager entry
	 */
	public long getId();

	/**
	 * Sets the ID of this file manager entry.
	 *
	 * @param id the ID of this file manager entry
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this file manager entry.
	 *
	 * @return the group ID of this file manager entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this file manager entry.
	 *
	 * @param groupId the group ID of this file manager entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this file manager entry.
	 *
	 * @return the company ID of this file manager entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this file manager entry.
	 *
	 * @param companyId the company ID of this file manager entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the account ID of this file manager entry.
	 *
	 * @return the account ID of this file manager entry
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this file manager entry.
	 *
	 * @param accountId the account ID of this file manager entry
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the create date of this file manager entry.
	 *
	 * @return the create date of this file manager entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this file manager entry.
	 *
	 * @param createDate the create date of this file manager entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this file manager entry.
	 *
	 * @return the modified date of this file manager entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this file manager entry.
	 *
	 * @param modifiedDate the modified date of this file manager entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the business ID of this file manager entry.
	 *
	 * @return the business ID of this file manager entry
	 */
	public long getBusinessId();

	/**
	 * Sets the business ID of this file manager entry.
	 *
	 * @param businessId the business ID of this file manager entry
	 */
	public void setBusinessId(long businessId);

	/**
	 * Returns the file ID of this file manager entry.
	 *
	 * @return the file ID of this file manager entry
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this file manager entry.
	 *
	 * @param fileId the file ID of this file manager entry
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the file type of this file manager entry.
	 *
	 * @return the file type of this file manager entry
	 */
	@AutoEscape
	public String getFileType();

	/**
	 * Sets the file type of this file manager entry.
	 *
	 * @param fileType the file type of this file manager entry
	 */
	public void setFileType(String fileType);

	/**
	 * Returns the file name of this file manager entry.
	 *
	 * @return the file name of this file manager entry
	 */
	@AutoEscape
	public String getFileName();

	/**
	 * Sets the file name of this file manager entry.
	 *
	 * @param fileName the file name of this file manager entry
	 */
	public void setFileName(String fileName);

	/**
	 * Returns the file size of this file manager entry.
	 *
	 * @return the file size of this file manager entry
	 */
	public Long getFileSize();

	/**
	 * Sets the file size of this file manager entry.
	 *
	 * @param fileSize the file size of this file manager entry
	 */
	public void setFileSize(Long fileSize);

	/**
	 * Returns the mime type of this file manager entry.
	 *
	 * @return the mime type of this file manager entry
	 */
	@AutoEscape
	public String getMimeType();

	/**
	 * Sets the mime type of this file manager entry.
	 *
	 * @param mimeType the mime type of this file manager entry
	 */
	public void setMimeType(String mimeType);

	/**
	 * Returns the module ID of this file manager entry.
	 *
	 * @return the module ID of this file manager entry
	 */
	@AutoEscape
	public String getModuleId();

	/**
	 * Sets the module ID of this file manager entry.
	 *
	 * @param moduleId the module ID of this file manager entry
	 */
	public void setModuleId(String moduleId);

	/**
	 * Returns the app ID of this file manager entry.
	 *
	 * @return the app ID of this file manager entry
	 */
	@AutoEscape
	public String getAppId();

	/**
	 * Sets the app ID of this file manager entry.
	 *
	 * @param appId the app ID of this file manager entry
	 */
	public void setAppId(String appId);

	/**
	 * Returns the project ID of this file manager entry.
	 *
	 * @return the project ID of this file manager entry
	 */
	public Long getProjectId();

	/**
	 * Sets the project ID of this file manager entry.
	 *
	 * @param projectId the project ID of this file manager entry
	 */
	public void setProjectId(Long projectId);

	/**
	 * Returns the phase ID of this file manager entry.
	 *
	 * @return the phase ID of this file manager entry
	 */
	public Long getPhaseId();

	/**
	 * Sets the phase ID of this file manager entry.
	 *
	 * @param phaseId the phase ID of this file manager entry
	 */
	public void setPhaseId(Long phaseId);

	/**
	 * Returns the work ID of this file manager entry.
	 *
	 * @return the work ID of this file manager entry
	 */
	public Long getWorkId();

	/**
	 * Sets the work ID of this file manager entry.
	 *
	 * @param workId the work ID of this file manager entry
	 */
	public void setWorkId(Long workId);

	@Override
	public FileManagerEntry cloneWithOriginalValues();

}