/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.core.project.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProjectEntry service. Represents a row in the &quot;SW_Project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.swork.core.project.service.model.impl.ProjectEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.swork.core.project.service.model.impl.ProjectEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectEntry
 * @generated
 */
@ProviderType
public interface ProjectEntryModel
	extends BaseModel<ProjectEntry>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project entry model instance should use the {@link ProjectEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this project entry.
	 *
	 * @return the primary key of this project entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project entry.
	 *
	 * @param primaryKey the primary key of this project entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this project entry.
	 *
	 * @return the uuid of this project entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this project entry.
	 *
	 * @param uuid the uuid of this project entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the project ID of this project entry.
	 *
	 * @return the project ID of this project entry
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this project entry.
	 *
	 * @param projectId the project ID of this project entry
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the group ID of this project entry.
	 *
	 * @return the group ID of this project entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this project entry.
	 *
	 * @param groupId the group ID of this project entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this project entry.
	 *
	 * @return the company ID of this project entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this project entry.
	 *
	 * @param companyId the company ID of this project entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the account ID of this project entry.
	 *
	 * @return the account ID of this project entry
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this project entry.
	 *
	 * @param accountId the account ID of this project entry
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the user name of this project entry.
	 *
	 * @return the user name of this project entry
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this project entry.
	 *
	 * @param userName the user name of this project entry
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this project entry.
	 *
	 * @return the create date of this project entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this project entry.
	 *
	 * @param createDate the create date of this project entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this project entry.
	 *
	 * @return the modified date of this project entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this project entry.
	 *
	 * @param modifiedDate the modified date of this project entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified ID of this project entry.
	 *
	 * @return the modified ID of this project entry
	 */
	public long getModifiedId();

	/**
	 * Sets the modified ID of this project entry.
	 *
	 * @param modifiedId the modified ID of this project entry
	 */
	public void setModifiedId(long modifiedId);

	/**
	 * Returns the name of this project entry.
	 *
	 * @return the name of this project entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this project entry.
	 *
	 * @param name the name of this project entry
	 */
	public void setName(String name);

	/**
	 * Returns the code of this project entry.
	 *
	 * @return the code of this project entry
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this project entry.
	 *
	 * @param code the code of this project entry
	 */
	public void setCode(String code);

	/**
	 * Returns the start date of this project entry.
	 *
	 * @return the start date of this project entry
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this project entry.
	 *
	 * @param startDate the start date of this project entry
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this project entry.
	 *
	 * @return the end date of this project entry
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this project entry.
	 *
	 * @param endDate the end date of this project entry
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the budget of this project entry.
	 *
	 * @return the budget of this project entry
	 */
	public long getBudget();

	/**
	 * Sets the budget of this project entry.
	 *
	 * @param budget the budget of this project entry
	 */
	public void setBudget(long budget);

	/**
	 * Returns the description of this project entry.
	 *
	 * @return the description of this project entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this project entry.
	 *
	 * @param description the description of this project entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the status of this project entry.
	 *
	 * @return the status of this project entry
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this project entry.
	 *
	 * @param status the status of this project entry
	 */
	public void setStatus(String status);

	/**
	 * Returns the progress of this project entry.
	 *
	 * @return the progress of this project entry
	 */
	public Integer getProgress();

	/**
	 * Sets the progress of this project entry.
	 *
	 * @param progress the progress of this project entry
	 */
	public void setProgress(Integer progress);

	/**
	 * Returns the actual time of this project entry.
	 *
	 * @return the actual time of this project entry
	 */
	public Date getActualTime();

	/**
	 * Sets the actual time of this project entry.
	 *
	 * @param actualTime the actual time of this project entry
	 */
	public void setActualTime(Date actualTime);

	/**
	 * Returns the actual start of this project entry.
	 *
	 * @return the actual start of this project entry
	 */
	public Date getActualStart();

	/**
	 * Sets the actual start of this project entry.
	 *
	 * @param actualStart the actual start of this project entry
	 */
	public void setActualStart(Date actualStart);

	/**
	 * Returns the progress type of this project entry.
	 *
	 * @return the progress type of this project entry
	 */
	@AutoEscape
	public String getProgressType();

	/**
	 * Sets the progress type of this project entry.
	 *
	 * @param progressType the progress type of this project entry
	 */
	public void setProgressType(String progressType);

	/**
	 * Returns the business ID of this project entry.
	 *
	 * @return the business ID of this project entry
	 */
	public long getBusinessId();

	/**
	 * Sets the business ID of this project entry.
	 *
	 * @param businessId the business ID of this project entry
	 */
	public void setBusinessId(long businessId);

	@Override
	public ProjectEntry cloneWithOriginalValues();

}