/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.common.comment.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CommentEntry service. Represents a row in the &quot;SW_Comment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.swork.common.comment.service.model.impl.CommentEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.swork.common.comment.service.model.impl.CommentEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CommentEntry
 * @generated
 */
@ProviderType
public interface CommentEntryModel
	extends BaseModel<CommentEntry>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a comment entry model instance should use the {@link CommentEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this comment entry.
	 *
	 * @return the primary key of this comment entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this comment entry.
	 *
	 * @param primaryKey the primary key of this comment entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this comment entry.
	 *
	 * @return the uuid of this comment entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this comment entry.
	 *
	 * @param uuid the uuid of this comment entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the comment ID of this comment entry.
	 *
	 * @return the comment ID of this comment entry
	 */
	public long getCommentId();

	/**
	 * Sets the comment ID of this comment entry.
	 *
	 * @param commentId the comment ID of this comment entry
	 */
	public void setCommentId(long commentId);

	/**
	 * Returns the group ID of this comment entry.
	 *
	 * @return the group ID of this comment entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this comment entry.
	 *
	 * @param groupId the group ID of this comment entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this comment entry.
	 *
	 * @return the company ID of this comment entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this comment entry.
	 *
	 * @param companyId the company ID of this comment entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the account ID of this comment entry.
	 *
	 * @return the account ID of this comment entry
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this comment entry.
	 *
	 * @param accountId the account ID of this comment entry
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the create date of this comment entry.
	 *
	 * @return the create date of this comment entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this comment entry.
	 *
	 * @param createDate the create date of this comment entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this comment entry.
	 *
	 * @return the modified date of this comment entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this comment entry.
	 *
	 * @param modifiedDate the modified date of this comment entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the business ID of this comment entry.
	 *
	 * @return the business ID of this comment entry
	 */
	public long getBusinessId();

	/**
	 * Sets the business ID of this comment entry.
	 *
	 * @param businessId the business ID of this comment entry
	 */
	public void setBusinessId(long businessId);

	/**
	 * Returns the content of this comment entry.
	 *
	 * @return the content of this comment entry
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this comment entry.
	 *
	 * @param content the content of this comment entry
	 */
	public void setContent(String content);

	/**
	 * Returns the parent ID of this comment entry.
	 *
	 * @return the parent ID of this comment entry
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this comment entry.
	 *
	 * @param parentId the parent ID of this comment entry
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the class pk ID of this comment entry.
	 *
	 * @return the class pk ID of this comment entry
	 */
	public long getClassPkId();

	/**
	 * Sets the class pk ID of this comment entry.
	 *
	 * @param classPkId the class pk ID of this comment entry
	 */
	public void setClassPkId(long classPkId);

	/**
	 * Returns the class pk name of this comment entry.
	 *
	 * @return the class pk name of this comment entry
	 */
	@AutoEscape
	public String getClassPKName();

	/**
	 * Sets the class pk name of this comment entry.
	 *
	 * @param classPKName the class pk name of this comment entry
	 */
	public void setClassPKName(String classPKName);

	@Override
	public CommentEntry cloneWithOriginalValues();

}