/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.auth.department.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DepartmentEntry service. Represents a row in the &quot;SW_Department&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.swork.auth.department.service.model.impl.DepartmentEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.swork.auth.department.service.model.impl.DepartmentEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DepartmentEntry
 * @generated
 */
@ProviderType
public interface DepartmentEntryModel
	extends BaseModel<DepartmentEntry>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a department entry model instance should use the {@link DepartmentEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this department entry.
	 *
	 * @return the primary key of this department entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this department entry.
	 *
	 * @param primaryKey the primary key of this department entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this department entry.
	 *
	 * @return the uuid of this department entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this department entry.
	 *
	 * @param uuid the uuid of this department entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this department entry.
	 *
	 * @return the external reference code of this department entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this department entry.
	 *
	 * @param externalReferenceCode the external reference code of this department entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the department ID of this department entry.
	 *
	 * @return the department ID of this department entry
	 */
	public long getDepartmentId();

	/**
	 * Sets the department ID of this department entry.
	 *
	 * @param departmentId the department ID of this department entry
	 */
	public void setDepartmentId(long departmentId);

	/**
	 * Returns the group ID of this department entry.
	 *
	 * @return the group ID of this department entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this department entry.
	 *
	 * @param groupId the group ID of this department entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this department entry.
	 *
	 * @return the company ID of this department entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this department entry.
	 *
	 * @param companyId the company ID of this department entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the account ID of this department entry.
	 *
	 * @return the account ID of this department entry
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this department entry.
	 *
	 * @param accountId the account ID of this department entry
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the create date of this department entry.
	 *
	 * @return the create date of this department entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this department entry.
	 *
	 * @param createDate the create date of this department entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified ID of this department entry.
	 *
	 * @return the modified ID of this department entry
	 */
	public long getModifiedId();

	/**
	 * Sets the modified ID of this department entry.
	 *
	 * @param modifiedId the modified ID of this department entry
	 */
	public void setModifiedId(long modifiedId);

	/**
	 * Returns the modified date of this department entry.
	 *
	 * @return the modified date of this department entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this department entry.
	 *
	 * @param modifiedDate the modified date of this department entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the business ID of this department entry.
	 *
	 * @return the business ID of this department entry
	 */
	public long getBusinessId();

	/**
	 * Sets the business ID of this department entry.
	 *
	 * @param businessId the business ID of this department entry
	 */
	public void setBusinessId(long businessId);

	/**
	 * Returns the name of this department entry.
	 *
	 * @return the name of this department entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this department entry.
	 *
	 * @param name the name of this department entry
	 */
	public void setName(String name);

	@Override
	public DepartmentEntry cloneWithOriginalValues();

}