/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.swork.auth.department.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DepartmentAccountEntry service. Represents a row in the &quot;SW_DepartmentAccount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.swork.auth.department.service.model.impl.DepartmentAccountEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.swork.auth.department.service.model.impl.DepartmentAccountEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DepartmentAccountEntry
 * @generated
 */
@ProviderType
public interface DepartmentAccountEntryModel
	extends BaseModel<DepartmentAccountEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a department account entry model instance should use the {@link DepartmentAccountEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this department account entry.
	 *
	 * @return the primary key of this department account entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this department account entry.
	 *
	 * @param primaryKey the primary key of this department account entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this department account entry.
	 *
	 * @return the uuid of this department account entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this department account entry.
	 *
	 * @param uuid the uuid of this department account entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this department account entry.
	 *
	 * @return the external reference code of this department account entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this department account entry.
	 *
	 * @param externalReferenceCode the external reference code of this department account entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the department account ID of this department account entry.
	 *
	 * @return the department account ID of this department account entry
	 */
	public long getDepartmentAccountId();

	/**
	 * Sets the department account ID of this department account entry.
	 *
	 * @param departmentAccountId the department account ID of this department account entry
	 */
	public void setDepartmentAccountId(long departmentAccountId);

	/**
	 * Returns the group ID of this department account entry.
	 *
	 * @return the group ID of this department account entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this department account entry.
	 *
	 * @param groupId the group ID of this department account entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this department account entry.
	 *
	 * @return the company ID of this department account entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this department account entry.
	 *
	 * @param companyId the company ID of this department account entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the department ID of this department account entry.
	 *
	 * @return the department ID of this department account entry
	 */
	public long getDepartmentId();

	/**
	 * Sets the department ID of this department account entry.
	 *
	 * @param departmentId the department ID of this department account entry
	 */
	public void setDepartmentId(long departmentId);

	/**
	 * Returns the account ID of this department account entry.
	 *
	 * @return the account ID of this department account entry
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this department account entry.
	 *
	 * @param accountId the account ID of this department account entry
	 */
	public void setAccountId(long accountId);

	@Override
	public DepartmentAccountEntry cloneWithOriginalValues();

}